### ISSUE TITLE
Support for `Set`

### ISSUE THREAD

**Issue by savvasdalkitsis** [jayasuryat/dowel#15]
**Is your feature request related to a problem? Please describe.**
Some basic collections are supported but `Set` is missing

**Describe the solution you'd like**
Set is added to the supported types

**Comment by jayasuryat** [comment]
Hey @savvasdalkitsis! 👋

Thanks for raising an issue for this,
Adding support for `Set<T>` should be fairly straightforward. I'll take care of it over the weekend.

**Comment by jayasuryat** [comment]
Hey @savvasdalkitsis,
Support for `Set<T>` has been added to `Dowel` as part of the `v0.8.0` release.
Check it out at your convenience.
